import type { MusicPlatform, MusicInfo } from '../../types';
import { httpFetch } from '../request';
import { arr, makeMusicInfo, normalizeCover, obj, page, staticSorts } from '../platform-common';

const headers={Referer:'https://app.c.nf.migu.cn/','User-Agent':'Mozilla/5.0','By':'migu',channel:'0146921'};
function collectPlaylists(value:unknown,result:Record<string,any>[]=[],seen=new Set<string>()):Record<string,any>[] {for(const item of arr(value)){const r=obj(item);const action=String(r.action||'');const actionId=/[?&]id=(\d+)/.exec(action)?.[1];const id=String(r.resId||actionId||obj(r.logEvent).contentId||'');if((String(r.resType)==='2021'||/song-list-info/.test(action))&&id&&!seen.has(id)){seen.add(id);result.push({...r,_playlistId:id});}if(Array.isArray(r.contents))collectPlaylists(r.contents,result,seen);}return result;}
function parseClock(value:unknown):unknown{const text=String(value||'');if(!/^\d{1,2}:\d{2}(?::\d{2})?$/.test(text))return value;return text.split(':').reduce((total,part)=>total*60+Number(part),0);}
export function parseMiguSong(raw:Record<string,any>):MusicInfo{const singers=raw.singers||raw.artists||raw.singerName||raw.singer;const id=raw.copyrightId||raw.copyrightid||raw.id||raw.songId;const albumImg=arr(raw.albumImgs)[0];return makeMusicInfo('mg',raw,{name:raw.songName||raw.name,singer:singers,album:raw.albumName||raw.album,duration:parseClock(raw.duration||raw.length),cover:normalizeCover(raw.cover||raw.coverUrl||obj(albumImg).img||raw.imgItems&&arr(raw.imgItems)[0]&&obj(arr(raw.imgItems)[0]).img),songmid:id,musicId:id,copyrightId:id,albumId:raw.albumId,extra:{types:[{type:'flac'},{type:'320k'},{type:'128k'}]}});}
const parseSong=parseMiguSong;
async function search(keyword:string,pageNo=1,limit=30){const {body,statusCode}=await httpFetch(`https://m.music.migu.cn/migu/remoting/scr_search_tag?rows=${limit}&type=2&keyword=${encodeURIComponent(keyword)}&pgc=${pageNo}`,{headers}).promise;if(statusCode>=400)throw new Error(`咪咕搜索失败: HTTP ${statusCode}`);const d=obj(body);const rows=arr(d.musics||obj(d.data).songs||d.songResultData);return page('mg',rows.map(x=>parseSong(obj(x))).filter(x=>x.name),pageNo,limit,Number(d.pgt||d.total||rows.length));}
async function getLyric(song:MusicInfo){const id=song.copyrightId||song.musicId||song.songmid;if(!id)throw new Error('咪咕歌曲缺少 copyrightId');const {body}=await httpFetch(`https://music.migu.cn/v3/api/music/audioPlayer/getLyric?copyrightId=${encodeURIComponent(id)}`,{headers}).promise;const d=obj(obj(body).data||body);return {lyric:String(d.lyric||d.lrc||''),tlyric:String(d.translatedLyric||''),raw:body};}
const boards=[{id:'27553319',name:'尖叫新歌榜'},{id:'27186466',name:'尖叫热歌榜'},{id:'27553408',name:'尖叫原创榜'},{id:'75959118',name:'音乐风向榜'}];
const mg:MusicPlatform={id:'mg',name:'咪咕音乐',musicSearch:{search},getLyric,
  songList:{
    async tags(){return {source:'mg',list:[{id:'1000001770',name:'推荐'},{id:'1000001749',name:'流行'},{id:'1000001754',name:'摇滚'}]};},
    async list(params){const pageNo=Number(params.page||1),limit=Number(params.limit||30);const tag=String(params.tag||'');const url=tag&&tag!=='1000001770'?`https://app.c.nf.migu.cn/pc/v1.0/template/musiclistplaza-listbytag/release?pageNumber=${pageNo}&templateVersion=2&tagId=${encodeURIComponent(tag)}`:`https://app.c.nf.migu.cn/pc/bmw/page-data/playlist-square-recommend/v1.0?templateVersion=2&pageNo=${pageNo}`;const {body}=await httpFetch(url,{headers}).promise;const d=obj(body);if(String(d.code)!=='000000')throw new Error(`咪咕热门歌单获取失败：${String(d.info||d.message||'上游接口异常')}`);const rows=collectPlaylists(obj(d.data).contents||obj(d.data).contentItemList);return {source:'mg',page:pageNo,limit,total:rows.length,list:rows.slice(0,limit).map(r=>({id:String(r._playlistId),name:String(r.txt||r.title||r.name||''),img:normalizeCover(r.img||r.imageUrl),playCount:Number(r.playCount||0),creator:String(r.creatorName||'')})).filter(x=>x.id&&x.name)};},
    async detail(id,pageNo=1,limit=100){const {body}=await httpFetch(`https://app.c.nf.migu.cn/MIGUM3.0/resource/playlist/song/v2.0?pageNo=${pageNo}&pageSize=${limit}&playlistId=${encodeURIComponent(id)}`,{headers}).promise;const d=obj(body);if(String(d.code)!=='000000')throw new Error(`咪咕歌单详情获取失败：${String(d.info||d.message||'上游接口异常')}`);const data=obj(d.data);const rows=arr(data.songList||data.songs||data.musicList);return {source:'mg',id,page:pageNo,limit,total:Number(data.totalCount||data.total||rows.length),name:data.title||data.name||'',img:normalizeCover(obj(data.imgItem).img||data.cover),list:rows.map(x=>parseSong(obj(x)))};},
    async search(keyword,pageNo=1,limit=30){const {body}=await httpFetch(`https://m.music.migu.cn/migu/remoting/scr_search_tag?rows=${limit}&type=6&keyword=${encodeURIComponent(keyword)}&pgc=${pageNo}`,{headers}).promise;const d=obj(body);const data=obj(d.data);const rows=arr(d.playLists||d.playlists||d.playListResultData||d.playlistResultData||data.playLists||data.playlists||data.list);return {source:'mg',page:pageNo,limit,total:Number(d.total||d.pgt||data.total||rows.length),list:rows.map(x=>{const r=obj(x);return {id:String(r.playlistId||r.playListId||r.id||r.contentId||''),name:String(r.playlistName||r.playListName||r.name||r.title||''),img:normalizeCover(r.imageUrl||r.img||r.cover||r.pic),playCount:Number(r.playCount||r.playNum||0),creator:String(r.creatorName||r.userName||r.nickname||''),description:String(r.summary||r.description||'')};}).filter(x=>x.id&&x.name)};},
    async sorts(){return staticSorts('mg');},
  },
  leaderboard:{
    async boards(){return {source:'mg',list:boards};},
    async list(id,pageNo=1,limit=100){const {body}=await httpFetch(`https://app.c.nf.migu.cn/MIGUM2.0/v1.0/content/querycontentbyId.do?columnId=${encodeURIComponent(id)}&needAll=0`,{headers}).promise;const d=obj(body);if(String(d.code)!=='000000')throw new Error(`咪咕排行榜获取失败：${String(d.info||d.message||'上游接口异常')}`);const column=obj(d.columnInfo);const rows=arr(column.contents).map(item=>obj(obj(item).objectInfo)).filter(item=>item.songId||item.copyrightId);return {source:'mg',id,page:pageNo,limit,total:Number(column.contentsCount||rows.length),list:rows.slice((pageNo-1)*limit,pageNo*limit).map(parseSong)};},
  }
};
export default mg;
